'use strict';
const $=s=>document.querySelector(s), TAU=Math.PI*2;
const el={camera:$('#camera'),canvas:$('#scene'),landing:$('#landing'),app:$('#app'),name:$('#nameInput'),room:$('#roomInput'),err:$('#landingError'),create:$('#createBtn'),join:$('#joinBtn'),demo:$('#demoBtn'),roomReadout:$('#roomReadout'),net:$('#netStatus'),members:$('#members'),targetCard:$('#targetCard'),targetName:$('#targetName'),targetMeta:$('#targetMeta'),menu:$('#menuBtn'),share:$('#shareBtn'),sheetShare:$('#sheetShare'),copy:$('#copyBtn'),shareCode:$('#shareCode'),cameraBtn:$('#cameraBtn'),rename:$('#renameBtn'),leave:$('#leaveBtn'),pulse:$('#pulseBtn'),drop:$('#dropBtn'),view:$('#viewBtn'),pulseOverlay:$('#pulseOverlay'),pulseText:$('#pulseText'),notice:$('#notice')};
const ctx=el.canvas.getContext('2d'); let W=0,H=0,DPR=1;
let peer=null,hostConn=null,isHost=false,isDemo=false,roomCode='',selfId='',displayName='',cameraStream=null,cameraOn=false,watchId=null;
let heading=null,orientationOk=false,selectedId=null,lastBroadcast=0,noticeTimer=0,radarOnly=false,demoStart=0;
const members=new Map(),connections=new Map(),beacons=new Map();
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;el.canvas.width=W*DPR;el.canvas.height=H*DPR;el.canvas.style.width=W+'px';el.canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize,{passive:true});resize();
const safeName=()=>((el.name.value||localStorage.cbName||'Beacon').trim().slice(0,18)||'Beacon');
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:7},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
function notify(msg){clearTimeout(noticeTimer);el.notice.textContent=msg;el.notice.classList.add('show');noticeTimer=setTimeout(()=>el.notice.classList.remove('show'),1500)}
function inviteUrl(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('room',roomCode);return u.toString()}
function hostPeerId(c){return 'crowdbeacon-'+c.toLowerCase()}
async function startSensors(){await Promise.allSettled([startCamera(),startOrientation()]);startLocation()}
async function startCamera(){if(cameraStream)return;try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});el.camera.srcObject=cameraStream;await el.camera.play();cameraOn=true;el.cameraBtn.textContent='CAMERA OFF'}catch(_){cameraOn=false;el.cameraBtn.textContent='CAMERA UNAVAILABLE';radarOnly=true;el.viewBtn.textContent='AR'}}
function stopCamera(){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;cameraOn=false;el.camera.srcObject=null;el.cameraBtn.textContent='CAMERA ON'}
async function startOrientation(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){if(await DeviceOrientationEvent.requestPermission()!=='granted')return}const handle=e=>{let h=null;if(Number.isFinite(e.webkitCompassHeading))h=e.webkitCompassHeading;else if(Number.isFinite(e.alpha))h=(360-e.alpha)%360;if(h!=null){heading=h;orientationOk=true}};addEventListener('deviceorientationabsolute',handle,true);addEventListener('deviceorientation',handle,true)}catch(_){}}
function startLocation(){if(!navigator.geolocation){el.net.textContent='NO GPS';return}watchId=navigator.geolocation.watchPosition(p=>{const c=p.coords;const me={id:selfId,name:displayName,type:'person',lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,heading:Number.isFinite(c.heading)?c.heading:null,speed:c.speed,updatedAt:Date.now(),host:isHost};members.set(selfId,me);sendLocation(me);renderMembers()},e=>{el.net.textContent=e.code===1?'GPS BLOCKED':'GPS ERROR';notify('LOCATION PERMISSION REQUIRED')},{enableHighAccuracy:true,maximumAge:1500,timeout:12000})}
function sendLocation(me){if(isDemo)return;const msg={type:'loc',member:me};if(isHost){broadcast({type:'state',members:[...members.values()],beacons:[...beacons.values()]})}else if(hostConn?.open){hostConn.send(msg)}}
function enterRoom(){localStorage.cbName=displayName;el.landing.classList.add('hidden');el.app.classList.remove('hidden');el.roomReadout.textContent='ROOM '+roomCode;el.shareCode.value=roomCode;document.body.classList.remove('sheetopen');startSensors();renderMembers()}
function createRoom(){displayName=safeName();roomCode=code();isHost=true;selfId='host-'+roomCode;enterRoom();if(typeof Peer==='undefined'){failPeer();return}peer=new Peer(hostPeerId(roomCode));peer.on('open',()=>{el.net.textContent='HOSTING';const me=members.get(selfId);if(me)members.set(selfId,{...me,host:true});notify('ROOM READY')});peer.on('connection',conn=>{connections.set(conn.peer,conn);conn.on('data',d=>handleHostData(conn,d));conn.on('close',()=>{const id=conn.metadata?.memberId||conn.peer;connections.delete(conn.peer);members.delete(id);broadcastState();renderMembers()})});peer.on('error',e=>{if(e.type==='unavailable-id'){roomCode=code();location.reload()}else{el.net.textContent='NETWORK ERROR';notify('PEER CONNECTION FAILED')}})}
function joinRoom(c){displayName=safeName();roomCode=(c||'').trim().toUpperCase();if(roomCode.length<5){el.err.textContent='Enter a valid room code.';return}isHost=false;selfId='guest-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36);enterRoom();if(typeof Peer==='undefined'){failPeer();return}peer=new Peer();peer.on('open',()=>{hostConn=peer.connect(hostPeerId(roomCode),{reliable:true,metadata:{memberId:selfId}});hostConn.on('open',()=>{el.net.textContent='CONNECTED';hostConn.send({type:'join',member:{id:selfId,name:displayName,type:'person',updatedAt:Date.now()}});const me=members.get(selfId);if(me)hostConn.send({type:'loc',member:me})});hostConn.on('data',handleClientData);hostConn.on('close',()=>{el.net.textContent='HOST LEFT';notify('ROOM CLOSED')});hostConn.on('error',()=>{el.net.textContent='CONNECTION ERROR'})});peer.on('error',()=>{el.net.textContent='ROOM NOT FOUND';notify('COULD NOT REACH HOST')})}
function failPeer(){el.net.textContent='NETWORK BLOCKED';notify('LIVE LINK SERVICE DID NOT LOAD')}
