'use strict';
function handleHostData(conn,d){if(!d||typeof d!=='object')return;if(d.type==='join'){connections.get(conn.peer).metadata={memberId:d.member.id};members.set(d.member.id,{...d.member,updatedAt:Date.now()});broadcastState();renderMembers()}else if(d.type==='loc'){members.set(d.member.id,sanitizeMember(d.member));broadcastState();renderMembers()}else if(d.type==='beacon'){const b=sanitizeMember(d.beacon);beacons.set(b.id,b);broadcastState();renderMembers()}else if(d.type==='pulse'){routePulse(d)}else if(d.type==='rename'){const m=members.get(d.id);if(m){m.name=String(d.name).slice(0,18);broadcastState();renderMembers()}}}
function sanitizeMember(m){return{id:String(m.id),name:String(m.name||'Beacon').slice(0,18),type:m.type==='beacon'?'beacon':'person',lat:Number(m.lat),lon:Number(m.lon),accuracy:Number(m.accuracy||0),heading:Number.isFinite(m.heading)?m.heading:null,speed:Number.isFinite(m.speed)?m.speed:null,updatedAt:Date.now(),host:!!m.host}}
function handleClientData(d){if(!d||typeof d!=='object')return;if(d.type==='state'){members.clear();d.members.forEach(m=>members.set(m.id,sanitizeMember(m)));beacons.clear();d.beacons.forEach(b=>beacons.set(b.id,sanitizeMember(b)));const mine=members.get(selfId);if(mine)mine.name=displayName;renderMembers()}else if(d.type==='pulse'&&d.to===selfId)receivePulse(d.fromName)}
function broadcast(msg){connections.forEach(c=>{if(c.open)try{c.send(msg)}catch(_){}})}function broadcastState(){broadcast({type:'state',members:[...members.values()],beacons:[...beacons.values()]})}
function routePulse(d){if(d.to===selfId)receivePulse(d.fromName);connections.forEach(c=>{if(c.open)c.send(d)})}
function receivePulse(from){el.pulseText.textContent=(from||'SOMEONE').toUpperCase()+' IS PINGING YOU';el.pulseOverlay.classList.remove('go');void el.pulseOverlay.offsetWidth;el.pulseOverlay.classList.add('go');navigator.vibrate?.([180,90,180,90,320])}
function allTargets(){return[...members.values(),...beacons.values()].filter(m=>m.id!==selfId&&Number.isFinite(m.lat)&&Number.isFinite(m.lon))}
function renderMembers(){const targets=allTargets();if(selectedId&&!targets.some(t=>t.id===selectedId))selectedId=null;if(!selectedId&&targets.length)selectedId=targets[0].id;el.members.innerHTML='';targets.forEach(m=>{const b=document.createElement('button');b.className='member'+(m.id===selectedId?' active':'');b.innerHTML='<div class="n">'+escapeHtml((m.type==='beacon'?'⌖ ':'')+m.name)+'</div><div class="d">'+targetDistance(m)+'</div>';b.onclick=()=>{selectedId=m.id;renderMembers()};el.members.appendChild(b)});const t=getTarget();if(t){el.targetCard.classList.remove('hidden');el.targetName.textContent=(t.type==='beacon'?'⌖ ':'')+t.name;const age=Math.floor((Date.now()-t.updatedAt)/1000);el.targetMeta.textContent=targetDistance(t)+' · '+(age<4?'LIVE':age+'s OLD');el.targetCard.classList.toggle('stale',age>12)}else{el.targetCard.classList.add('hidden')}}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function getTarget(){return members.get(selectedId)||beacons.get(selectedId)||null}function getMe(){return members.get(selfId)||null}
function hav(a,b){const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function bearing(a,b){const p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function delta(a,b){let d=a-b;while(d>180)d-=360;while(d<-180)d+=360;return d}
function units(m){if(!Number.isFinite(m))return'WAITING FOR GPS';const ft=m*3.28084;if(ft<1000)return Math.round(ft)+' FT';return(m/1609.344).toFixed(m<16093?1:0)+' MI'}
function targetDistance(t){const me=getMe();return me?units(hav(me,t)):'WAITING FOR GPS'}
function dropSpot(){const me=getMe();if(!me){notify('WAITING FOR GPS');return}const b={id:'spot-'+Date.now(),name:'MEETING SPOT',type:'beacon',lat:me.lat,lon:me.lon,accuracy:me.accuracy,updatedAt:Date.now()};beacons.set(b.id,b);selectedId=b.id;if(isHost){broadcastState()}else hostConn?.send({type:'beacon',beacon:b});renderMembers();notify('MEETING SPOT DROPPED')}
function pulseTarget(){const t=getTarget();if(!t){notify('SELECT A PERSON FIRST');return}if(t.type==='beacon'){notify('A SPOT CANNOT RECEIVE A PULSE');return}const msg={type:'pulse',to:t.id,from:selfId,fromName:displayName};if(isDemo){receivePulse('DEMO FRIEND');return}if(isHost)routePulse(msg);else hostConn?.send(msg);navigator.vibrate?.(35);notify('PULSE SENT')}
function shareInvite(){const data={title:'Join my CrowdBeacon',text:'Open this link so I can point toward you in the crowd. Room '+roomCode,url:inviteUrl()};if(navigator.share)navigator.share(data).catch(()=>{});else navigator.clipboard?.writeText(inviteUrl()).then(()=>notify('INVITE LINK COPIED'))}
function rename(){const n=prompt('Display name',displayName);if(!n)return;displayName=n.trim().slice(0,18)||displayName;localStorage.cbName=displayName;const me=members.get(selfId);if(me)me.name=displayName;if(isHost)broadcastState();else hostConn?.send({type:'rename',id:selfId,name:displayName});renderMembers();notify('NAME UPDATED')}
function leave(){cameraStream?.getTracks().forEach(t=>t.stop());if(watchId!=null)navigator.geolocation.clearWatch(watchId);connections.forEach(c=>c.close());hostConn?.close();peer?.destroy();location.href=location.pathname}
function demo(){displayName=safeName();roomCode='DEMO';isDemo=true;isHost=true;selfId='demo-self';enterRoom();el.net.textContent='DEMO';demoStart=performance.now();const lat=42.932,lon=-76.566;members.set(selfId,{id:selfId,name:displayName,type:'person',lat,lon,accuracy:4,updatedAt:Date.now(),host:true});members.set('demo-friend',{id:'demo-friend',name:'RICK',type:'person',lat:lat+.00018,lon:lon+.00013,accuracy:5,updatedAt:Date.now()});renderMembers()}
